[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "ab11c702c08066949931fa360f7d9a0e1e2e862a"
lazy = true
mpi = "mpich"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "74251dc984bc8e24a038edbb3af9d9dffcab6f7ddaf0c8a47bf6b7fc56635f8e"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "4a790e8528e2e5422dc82925dc7c2eceeb90d510"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "2f560cb7719ab2c4def7fb2d23adf92d7d8751d0018ff8d531a14f4a14b42a10"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "155fd2ba5b60f72a75587ee5f30f95b41d74c8f1"
lazy = true
mpi = "openmpi"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "9dc21ea533fac86ce7e179d0bbc9e0f142f9e9cc1e0bb69334106a1eda5dd547"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-apple-darwin-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "ef7fd8e2460101b9f30e43240ba8edf0c40c2a53"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "fb6b27a4e38bf9a565e6afa7f6ac30eda580f79d589034e40201fa89a82b9f12"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "21392f638dd53a861516d37aa195c30c409b97fd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "e68192469a57ba0f2e1fd5d968f15438b3c26c06c124c83cdce5421093958c1e"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "35ee9989c9791dc8b2b3906c32498fb8c04d3621"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "2a65a5cdcf96f05df4379e247b04ac361b074a67c984eb1b10b204196807bbeb"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-linux-gnu-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "cd0a957b65e0a046b7f1bae98afbc4310cf59206"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "f2deb8e3d7dd7f172d43bf38a9216703d7ad76bf4addf4bb978297a4425c5628"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-linux-musl-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "25e0fe63d045ce8e3fe38de215a0ae57d271c6b3"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "a2b656ebc0ef31553c106b5696139060cb7fdcf93f4a7d9c2cb6da952ad90758"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.aarch64-linux-musl-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e1dc60384e9deda752f6faa9797dca919da84a3a"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "0d803718550b2b4ee65dc3ed3809cd608d7060a6684e7dd57283002fb6c753b4"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "ddee9b23b44f509dc2a2f8ad229e13b3665642fd"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "97dd9c3197db0673abdadf768bda4f5aa9882aacaefd1f05193da08da11d7a42"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "42310fb8e3512af2f093b30bae984b33191f9c0f"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "d765e7bc95d683117959c4b7a980489677a2b47dbfe8b55a659376513c43c4fc"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "6917c8970c31a5dcf72c071bce080adab59f48de"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "f4089397614c9f5875335feee453f2c7434d1a8658320e8e4ca88bd3a45f331b"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv6l-linux-musleabihf-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d2da665d9a72d1be3452b5bef1fc4dcea1cd2cac"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "0140ae08c65bbed5bae76c98aeacb71bd631eec9cec8f38abf7b3e06d24cdf8a"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f67d7ef372e108f53f54c6e69e20fd7bc2ae7b41"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "e12157e91415ed03e097d5477331b3f2cd16a6fe3d0ea068c85f5235a92bfcec"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "633d45c807cc09d6ee08ee4a698a9b0fde11e7f5"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "7c68d4b7c092640d7ecdd5b6e7187a45fb2934802ebb9fea073e53c7b5e4cae9"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv7l-linux-gnueabihf-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "150ec53702a063074ddcd649e751c7e945d9dd45"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "501c6980d8d53659eaf3be655ea7fb0dd62dc791ca524cceba4b15794dfc1f14"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0570180e5efabd15660ad64e7e21cd7e98ee53aa"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "71c0f7aceb0352864de7060cfbacec393a3305f95f6affd52637aa8eae1228eb"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.armv7l-linux-musleabihf-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "372ebd83268fee4be559326359619e020fb1434f"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "97058953bcbc7d44771548b809bc0bbe03ca565457ce6f12da333dd38c17e829"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.i686-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "8c3f28d062faff5a9bea0767a83c53d50abce982"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "255325a2eb09fe1df933efc744e065c300abee666e175fe75e0fbe7b3eee7b02"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "b95298cc7771606ce2faf8ae63522c6278a281ad"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "09df85e9693ea14a5d87d3d553291edfa1a97a9bc49dea48731f4dfd39933e8c"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.i686-linux-gnu-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "4b136470d683cf07f8f1ec847553ee6c4420a039"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "16fe3b55f98c88ca74da7f52c43fffb7ea44c0697396e9bfa1bc47969b01f14e"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.i686-linux-musl-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "e31ba8ef7dc0dd543ed88fd3f4e240e3756f3500"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "ef9bec3e8bab915eb07e9afa7d58ca2790ea8a78c9781fe6bc6adb7290a11428"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.i686-linux-musl-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "de5445d164e89ab2d33c598293ad449c45b7b7ff"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "ff94c1a572a99530d4d354726170773170f1bacb9babdc5e90c363a052bf4363"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "b334ad20cffae7e38a165119f5f2d5deb46547a8"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "fead92adcd71ed843fb608c4ff1bcef1ae2299239ee2d21c4a305ccc3cd25c6f"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "1a0106fe7259816418a399be6a61df719a7b0ca5"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "017fe80d43229e01000714ef9f2a23d4ce405487e204551657da6fb3254a4fa1"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.powerpc64le-linux-gnu-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "c51b54c5cf307066eb61f3bca3a2c9158488955a"
lazy = true
mpi = "mpich"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "cbc3d7d34ead62d27efbd9f9767566dc35e52ab8df2781abcace7fafd55d6216"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "515a73dcb51d85b57f548c5ffbb7389e7b80fb17"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "886b8a3cd39baf79e58747ceb8cb78a84da52e788cdb6a6806e0aa6ca666a5f9"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "7126b819b97d028cc5eee6f2f074165fc1e8f771"
lazy = true
mpi = "openmpi"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "d699c0396ed7276f99e978848fd6e5f53f9a999d777e86301dbd4f64f1113997"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-apple-darwin-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "caffdc55b95700105f8a8466ec7e9a8484e0363d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "48810f4686b6e623d0b0bfa27316dbb5b30958adb7a6e7c7fa279235e09abec5"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "a7db1dd82ab3df3728ac746d87ab028bb230e21e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "a9eb1ac0e660d352114b7c9c7695e98942c1a0f9a86f72d717d5d30499c8f0be"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "f68289c4ad61a4b3a92d70b401a67d241aee4165"
lazy = true
libc = "glibc"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "84e35cb8bcccaef58bc94dc59529041bf965dcabf315cab04c295ab7597f1937"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-linux-gnu-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "59941315ea1764978df93570f48db7222ccaa14c"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "8233094a67d0fd2071f00e45b9b1377982d826735960927adbc28bed3820f2d0"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-linux-musl-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "b167b97c7eb4f113ed552977a06c56acc031e0f8"
lazy = true
libc = "musl"
mpi = "openmpi"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "e46e52671a1923b600e6e6cea1581b5898d7c487fded8870b57ff22f3ef28f14"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-linux-musl-mpi+openmpi.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "55696fae3144ff7b9d332f133cded2293adaea55"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[PTSCOTCH.download]]
    sha256 = "516fa14eecb9c7ff9ed38a7d78badd175e8cd9457730240048045f02b9f5b5d6"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "a1ddaaf9cf83001078ba1d43ff1ff743e8c3ab65"
lazy = true
mpi = "openmpi"
os = "freebsd"

    [[PTSCOTCH.download]]
    sha256 = "86e872f6eb515e836185131e632a392123558e19465bdafce77a446c21fae42e"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v7.0.4+0/PTSCOTCH.v7.0.4.x86_64-unknown-freebsd-mpi+openmpi.tar.gz"
