[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "fd1492b314ea526d5cff62cd002d05cb52320410"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "c20913e7d1ce535edaf5f723f24c92873ffa4b3ada47561c0f0ff305547f5f5a"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.aarch64-apple-darwin.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "437e4a468df657baf30672fce4ff138befc2a09b"
libc = "glibc"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "dad2584abc9cb3e4d6c1650aa1c74fc8d06194e609b1349f7f4548709b7125f1"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.aarch64-linux-gnu.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "b104eb745d0c19c126885f8ea58440d8ca664d99"
libc = "musl"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "4e776aadacdc7fe1823fd1c1525147a8437ed02ea431f0881d2da3f82f485318"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.aarch64-linux-musl.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "23426234cd8d430c42b64afdea3b7ec50288ebf2"
libc = "glibc"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "47f3e4c55bdd7ae398b0d7f4817d44117daae122bb155eae729b56278732764e"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.armv6l-linux-gnueabihf.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fccbf258291858ebaddc2562a0fac135f01ea1df"
libc = "musl"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "55f1f84848421abfc2a8152886d262dca1c792ee0ab845b1045a4b612a3f8770"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.armv6l-linux-musleabihf.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6cc90b797027f321b9f3ef0c8d6a569c8267f6e0"
libc = "glibc"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "13c8ebfcb67e8dc776cca84828cceb841fa46aae969777fa5a7e130c2831d9a8"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.armv7l-linux-gnueabihf.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ef4b9bcb6fc380fc39069ac51e39e8d4cb6a19e3"
libc = "musl"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "eed0dd2d969d1f8c0a8b7fb27d2bb04ef1444c341245fef3daad52e877763778"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.armv7l-linux-musleabihf.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "c8504baa208dc61acd634707ee2322c1527e3eec"
libc = "glibc"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "2a361f046ba7b6cf2b93411b73d73a1c0ad448c9f54fcf4940ee8e8bd718e0e6"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.i686-linux-gnu.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "c8d98f548aa6b4adb79a8c636456885c89695d5c"
libc = "musl"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "84b028f4f78428262cf5f1ce3dfdd573849f5660f96da4a59f0d3dbe5cfcc04f"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.i686-linux-musl.tar.gz"
[[PTSCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "0317d414fc332fc96396ab234a1054adf29e8f47"
libc = "glibc"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "80865c15552bd23669be54c64d00cb6b4f31790d1a10e8a5fa6b962287511ca1"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.powerpc64le-linux-gnu.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "01168c400962f29bf24c743f7ca67e22f02140ef"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "7e787d3964e1f3719a7ff9f8fb6f82b74032a6e62d703f65e494c32f19fc0f47"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.x86_64-apple-darwin.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "d143daa95e3216568dd611f44c6fd96adc56bec2"
libc = "glibc"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "10425a52cdbea8a126756d723c0ceacb961d5208a956b335ef70429fb45b1c8f"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.x86_64-linux-gnu.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "9200dc3e53784382667303d136d83d87b17f6dc2"
libc = "musl"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "baede8b8d85629ddf4a891e21d7c4bb2323a19490ac32017e8dcce03a99dd9bd"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.x86_64-linux-musl.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "545d2eda86795efc184f50d047f99aac728dabbb"
os = "freebsd"

    [[PTSCOTCH.download]]
    sha256 = "b1f22886fd5737507cc149dba698ca805728178df92bd9c3b7039f1d4191e19d"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.3+0/PTSCOTCH.v6.1.3.x86_64-unknown-freebsd.tar.gz"
