[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "7f26abdb75a4ca0e00015306dda7eb1a20add3df"
lazy = true
mpi = "mpich"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "eab1e6f498e7cf8448e0cabf8f0972ee5f257fd6e427ccd7af3b3c000208012f"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.aarch64-apple-darwin-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "b14534e045ebf3874583a6ab3d61fcfca70d026c"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "f6519e846c66f3718c038f8a61fac93193b48790e6a57b6381ddb9922deac518"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.aarch64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "5c79a8f4e5a1b6e24246e693d94b27bfcef3cfa1"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "e0bbec6b872b37581c59bde320ddc9f7c3a7ab37ad3da37c5b6e697707b4b12f"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.aarch64-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "f580de4f610a6f6fd51d8e378cbc162da6a6ef93"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "4e0bfd5a6465f6be3d028a35e4e0124e0b9ce27b33254aade0975535e0e5756e"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.aarch64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "aarch64"
git-tree-sha1 = "15035585fedf9c873b8c3c0e87fe2dfa6ec9c112"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "60f670ae2fbc4d71cb9e03ba45ac0fe017b586bf37ee73e7981c05f076712328"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.aarch64-linux-musl-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81e4b4b7a2c3a021612acdcc78a5a08a37d870ea"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "d443afebd649788aa5ae1ccd06544f890dd0b3ab0a728dae3f9f69b51107bea0"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.armv6l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "85b3674e2eb457a20faddc63ea7ba3f6988b0b7a"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "e365d3bb73beffa41d2be15515384835824fe693236a654932b24bfc428a0789"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.armv6l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b5c6abbfde319499e9a57b68aadafdfceff6d733"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "6180a9dd1c9052aac7d9dc7e9768eff69dc89dc655e9d4b7d295c1bd19560d3a"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.armv6l-linux-musleabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "bd28dd0a183103472731149f342b46c83e3e54fb"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "fdb82ce6d0004da3ca364e978a3df2cdb2256ead16d798fe388ac2e168de416a"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.armv7l-linux-gnueabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ad7ec45b5029aabbce81ef651ae407d881b7b2c4"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "2793e082c879dd96ddeaf33eb69b51545d7195afdf134f2704cb19c7a8a67f26"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.armv7l-linux-gnueabihf-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "fe7a525e3318ca3ab0722fb291b8ac1fe95d435a"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "273c3467dcd4f9f39742421b845c6b0f0083cb43d8671325a5abb21e2c5e428d"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.armv7l-linux-musleabihf-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "0dd98137e0e94be2d3c95840fa3c5938ca0ba62d"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "d5c90525654cecbc800cd3c4f0255c011e0a27ec6f0769f5d22de1fade822082"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.i686-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "5a075844c043d732893953210d1bad98c4e0b26b"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "0dfb77dbfc6e5ea781e6bda2729e36449207656b0bfb72c2b3201c2b64b2dde3"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.i686-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "i686"
git-tree-sha1 = "63ad45b6c1a6d1643c18d1b93c9274b258f827d9"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "d1976cfccc3c0d123c2b7b57c0a6792e16f432d911d7ac41e4edfb9d494121b9"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.i686-linux-musl-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "1128a025d200fda9a099eb76ed6035cf4645a35e"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "ffaba047872c769f34f23db61497ee0fd910147f5e2477e3f686424b56aa00d2"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.powerpc64le-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "powerpc64le"
git-tree-sha1 = "e390ff8535d010c522765b079a64c32bd94bc785"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "2ade764da8e7ea707e49eade1815e8737acfdc737d33bbbf00f98d625de0ec75"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.powerpc64le-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "e8fca3adafc477da2ac7793fff7aa2cb00650441"
lazy = true
mpi = "mpich"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "3bde250aee629d72d54aa3d4b5c2b27a4cb35e21313a4e92991728a91063a54f"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.x86_64-apple-darwin-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "1455857d82ce8026a9e21cd0e4cee017576a10cf"
lazy = true
mpi = "mpitrampoline"
os = "macos"

    [[PTSCOTCH.download]]
    sha256 = "9a9a57e6776341bde92a3d0e58b4448eac06140dbe3b9dbc6a59de026b1f8483"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.x86_64-apple-darwin-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "ef4f46a9a714486d12ce836ea8f542c2660bae79"
lazy = true
libc = "glibc"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "1f2bea0339380f037c040e6c782c622987c1af61e24f078bcb8b9cc8a85a9e75"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.x86_64-linux-gnu-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "20ea44f194680290cd2748ef0eb650047225af3e"
lazy = true
libc = "glibc"
mpi = "mpitrampoline"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "61cabc4664190da6ba6077bd4cb2d1496ff93deb11d2f0f6f5b2b7752439b739"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.x86_64-linux-gnu-mpi+mpitrampoline.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "89b94f20325e3f3256fed027ce569cdb0aef3345"
lazy = true
libc = "musl"
mpi = "mpich"
os = "linux"

    [[PTSCOTCH.download]]
    sha256 = "adcd39323f218fc3ba701168c172bd132de160b1f5ff3c9037e812b718855f40"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.x86_64-linux-musl-mpi+mpich.tar.gz"
[[PTSCOTCH]]
arch = "x86_64"
git-tree-sha1 = "67c60f6859558d63cea49728228833c5553526aa"
lazy = true
mpi = "mpich"
os = "freebsd"

    [[PTSCOTCH.download]]
    sha256 = "ad2b4ccbe2a6431f793edb191bf3648c595f8fcb05fd208eb5b59cd8fcca5284"
    url = "https://github.com/JuliaBinaryWrappers/PTSCOTCH_jll.jl/releases/download/PTSCOTCH-v6.1.4+1/PTSCOTCH.v6.1.4.x86_64-unknown-freebsd-mpi+mpich.tar.gz"
