# Autogenerated wrapper script for PTSCOTCH_jll for i686-linux-gnu-mpi+openmpi
export libptesmumps, libptscotch, libptscotcherr, libptscotcherrexit, libptscotchparmetisv3

using CompilerSupportLibraries_jll
using Zlib_jll
using Bzip2_jll
using XZ_jll
using SCOTCH_jll
using OpenMPI_jll
JLLWrappers.@generate_wrapper_header("PTSCOTCH")
JLLWrappers.@declare_library_product(libptesmumps, "libptesmumps.so")
JLLWrappers.@declare_library_product(libptscotch, "libptscotch.so")
JLLWrappers.@declare_library_product(libptscotcherr, "libptscotcherr.so")
JLLWrappers.@declare_library_product(libptscotcherrexit, "libptscotcherrexit.so")
JLLWrappers.@declare_library_product(libptscotchparmetisv3, "libptscotchparmetisv3.so")
function __init__()
    JLLWrappers.@generate_init_header(CompilerSupportLibraries_jll, Zlib_jll, Bzip2_jll, XZ_jll, SCOTCH_jll, OpenMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libptesmumps,
        "lib/libptesmumps.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libptscotch,
        "lib/libptscotch.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libptscotcherr,
        "lib/libptscotcherr.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libptscotcherrexit,
        "lib/libptscotcherrexit.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libptscotchparmetisv3,
        "lib/libptscotchparmetisv3.so",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
